#!/bin/zsh

# ------------------------------
# Launchd helpers (sourced)
# ------------------------------
launchd_support_root() {
  printf '%s' "${NOTES_SNAPSHOT_EXTERNAL_CACHE_ROOT:-${XDG_CACHE_HOME:-$HOME/.cache}/apple-notes-snapshot}"
}

launchd_ascii_root() {
  printf '%s' "$(launchd_support_root)"
}

launchd_legacy_support_root() {
  printf '%s' "${HOME}/Library/Application Support/AppleNotesSnapshot"
}

launchd_legacy_ascii_root() {
  printf '%s' "${HOME}/Library/ApplicationSupport/AppleNotesSnapshot"
}

launchd_bridge_root() {
  printf '%s' "$(launchd_support_root)/launchd"
}

launchd_runtime_repo_root() {
  local instance_key="$1"
  printf '%s' "$(launchd_ascii_root)/repos/${instance_key}"
}

launchd_runtime_data_root() {
  local instance_key="$1"
  printf '%s' "$(launchd_support_root)/runtime/${instance_key}"
}

launchd_runtime_root() {
  printf '%s' "$(launchd_support_root)/runtime"
}

launchd_repos_root() {
  printf '%s' "$(launchd_ascii_root)/repos"
}

launchd_legacy_launchd_root() {
  printf '%s' "$(launchd_legacy_support_root)/launchd"
}

launchd_legacy_runtime_root() {
  printf '%s' "$(launchd_legacy_support_root)/runtime"
}

launchd_legacy_repos_root() {
  printf '%s' "$(launchd_legacy_ascii_root)/repos"
}

launchd_vendor_runtime_root() {
  printf '%s' "$(launchd_support_root)/vendor-runtime"
}

launchd_legacy_vendor_runtime_root() {
  printf '%s' "${HOME}/Library/Caches/AppleNotesSnapshot/vendor-runtime"
}

launchd_browser_root() {
  printf '%s' "${NOTES_SNAPSHOT_BROWSER_ROOT:-$(launchd_support_root)/browser}"
}

launchd_browser_user_data_root() {
  printf '%s' "${NOTES_SNAPSHOT_CHROME_USER_DATA_DIR:-$(launchd_browser_root)/chrome-user-data}"
}

launchd_browser_temp_root() {
  printf '%s' "${NOTES_SNAPSHOT_BROWSER_TEMP_ROOT:-$(launchd_browser_root)/tmp}"
}

launchd_trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

launchd_build_calendar_block() {
  local calendar_minutes="$1"
  local -a minutes_list
  local minutes_count=0
  local block=$'  <key>StartCalendarInterval</key>\n  <array>\n'

  minutes_list=(${(s:,:)calendar_minutes})
  for minute in "${minutes_list[@]}"; do
    local trimmed
    trimmed="$(launchd_trim "$minute")"
    if [[ -z "$trimmed" ]]; then
      continue
    fi
    if [[ ! "$trimmed" =~ ^[0-9]+$ ]]; then
      die "invalid calendar minute: $trimmed"
    fi
    if [[ "$trimmed" -lt 0 || "$trimmed" -gt 59 ]]; then
      die "calendar minute out of range: $trimmed"
    fi
    block+=$'    <dict>\n      <key>Minute</key>\n      <integer>'"$trimmed"$'</integer>\n    </dict>\n'
    minutes_count=$((minutes_count + 1))
  done

  if [[ "$minutes_count" -eq 0 ]]; then
    die "NOTES_SNAPSHOT_CALENDAR_MINUTES provided but no valid minutes found"
  fi
  block+=$'  </array>'
  printf '%s' "$block"
}

launchd_build_schedule_block() {
  local interval_sec="$1"
  local calendar_minutes="$2"

  if [[ -n "$calendar_minutes" ]]; then
    launchd_build_calendar_block "$calendar_minutes"
    return 0
  fi
  if [[ "$interval_sec" -eq 1800 ]]; then
    printf '%s' $'  <key>StartCalendarInterval</key>\n  <array>\n    <dict>\n      <key>Minute</key>\n      <integer>0</integer>\n    </dict>\n    <dict>\n      <key>Minute</key>\n      <integer>30</integer>\n    </dict>\n  </array>'
    return 0
  fi
  printf '%s' $'  <key>StartInterval</key>\n  <integer>'"$interval_sec"$'</integer>'
}

launchd_build_paths_block() {
  local key="$1"
  local csv="$2"
  if [[ -z "$csv" ]]; then
    return 0
  fi

  local -a items
  local count=0
  local block=$'  <key>'"$key"$'</key>\n  <array>\n'

  items=(${(s:,:)csv})
  for path_item in "${items[@]}"; do
    local trimmed
    trimmed="$(launchd_trim "$path_item")"
    if [[ -z "$trimmed" ]]; then
      continue
    fi
    validate_path "$trimmed"
    block+=$'    <string>'"$trimmed"$'</string>\n'
    count=$((count + 1))
  done

  if [[ "$count" -eq 0 ]]; then
    return 0
  fi
  block+=$'  </array>'
  printf '%s' "$block"
}

launchd_build_throttle_block() {
  local throttle_sec="$1"
  if [[ -z "$throttle_sec" ]]; then
    return 0
  fi
  validate_int "NOTES_SNAPSHOT_LAUNCHD_THROTTLE_SEC" "$throttle_sec"
  printf '%s' $'  <key>ThrottleInterval</key>\n  <integer>'"$throttle_sec"$'</integer>'
}

launchd_write_plist() {
  local path="$1"
  local label="$2"
  local wrapper_script="$3"
  local log_dir="$4"
  local schedule_block="$5"
  local watch_block="$6"
  local queue_block="$7"
  local throttle_block="$8"

  cat <<PLIST > "$path"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <!-- Generated by notesctl install. Do not edit by hand. -->
  <key>Label</key>
  <string>${label}</string>

  <key>ProgramArguments</key>
  <array>
    <string>${wrapper_script}</string>
  </array>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>NOTES_SNAPSHOT_TRIGGER_SOURCE</key>
    <string>launchd</string>
  </dict>

${schedule_block}

  <key>RunAtLoad</key>
  <true/>

${watch_block}

${queue_block}

${throttle_block}

  <key>StandardOutPath</key>
  <string>${log_dir}/launchd.out.log</string>

  <key>StandardErrorPath</key>
  <string>${log_dir}/launchd.err.log</string>
</dict>
</plist>
PLIST
}

# ------------------------------
# Web UI plist (long-running service)
# ------------------------------
launchd_write_web_plist() {
  local path="$1"
  local label="$2"
  local python_bin="$3"
  local web_script="$4"
  local log_dir="$5"
  local web_host="$6"
  local web_port="$7"
  local cmd_timeout="$8"
  local repo_root="$9"
  local state_dir="${10}"
  local web_require_token="${11}"
  local web_require_token_for_static="${12}"
  local web_token="${13}"
  local web_allow_remote="${14}"
  local web_allow_ips="${15}"
  local web_token_scopes="${16}"
  local web_readonly="${17}"
  local web_actions_allow="${18}"
  local web_max_tail_lines="${19}"
  local web_rate_limit_window="${20}"
  local web_rate_limit_max="${21}"
  local web_action_cooldowns="${22}"

  cat <<PLIST > "$path"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <!-- Generated by notesctl install. Do not edit by hand. -->
  <key>Label</key>
  <string>${label}</string>

  <key>ProgramArguments</key>
  <array>
    <string>${python_bin}</string>
    <string>${web_script}</string>
    <string>--host</string>
    <string>${web_host}</string>
    <string>--port</string>
    <string>${web_port}</string>
  </array>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>

  <key>WorkingDirectory</key>
  <string>${repo_root}</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>NOTES_SNAPSHOT_LOG_DIR</key>
    <string>${log_dir}</string>
    <key>NOTES_SNAPSHOT_STATE_DIR</key>
    <string>${state_dir}</string>
    <key>NOTES_SNAPSHOT_WEB_CMD_TIMEOUT_SEC</key>
    <string>${cmd_timeout}</string>
    <key>NOTES_SNAPSHOT_WEB_REQUIRE_TOKEN</key>
    <string>${web_require_token}</string>
    <key>NOTES_SNAPSHOT_WEB_REQUIRE_TOKEN_FOR_STATIC</key>
    <string>${web_require_token_for_static}</string>
    <key>NOTES_SNAPSHOT_WEB_TOKEN</key>
    <string>${web_token}</string>
    <key>NOTES_SNAPSHOT_WEB_ALLOW_REMOTE</key>
    <string>${web_allow_remote}</string>
    <key>NOTES_SNAPSHOT_WEB_ALLOW_IPS</key>
    <string>${web_allow_ips}</string>
    <key>NOTES_SNAPSHOT_WEB_TOKEN_SCOPES</key>
    <string>${web_token_scopes}</string>
    <key>NOTES_SNAPSHOT_WEB_READONLY</key>
    <string>${web_readonly}</string>
    <key>NOTES_SNAPSHOT_WEB_ACTIONS_ALLOW</key>
    <string>${web_actions_allow}</string>
    <key>NOTES_SNAPSHOT_WEB_MAX_TAIL_LINES</key>
    <string>${web_max_tail_lines}</string>
    <key>NOTES_SNAPSHOT_WEB_RATE_LIMIT_WINDOW_SEC</key>
    <string>${web_rate_limit_window}</string>
    <key>NOTES_SNAPSHOT_WEB_RATE_LIMIT_MAX</key>
    <string>${web_rate_limit_max}</string>
    <key>NOTES_SNAPSHOT_WEB_ACTION_COOLDOWNS</key>
    <string>${web_action_cooldowns}</string>
  </dict>

  <key>StandardOutPath</key>
  <string>${log_dir}/webui.out.log</string>
  <key>StandardErrorPath</key>
  <string>${log_dir}/webui.err.log</string>
</dict>
</plist>
PLIST
}
